### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Marcelhag** [Marcelhag/phyphox-mpy#12]
- [ ]  Namespaces
- [x]  Import only phyphoxBLE
- [x]  Filestructure
- [x]  remove XML
- [x]  Lower/uppercase (BLE)
- [x]  TypeError: can't convert NoneType to float
- [x]  Remove prints
- [x]  ReadMe
- [ ]  Anleitung
